# Generated by Django 5.2.7 on 2026-04-22 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0023_sharedtimetable_social_sync_fields"),
        ("student", "0046_delete_registrationtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharedtimetable",
            name="edit_token",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="sharedtimetable",
            name="revision",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="SharedTimetableOperation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_type", models.CharField(max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("base_revision", models.PositiveIntegerField()),
                ("applied_revision", models.PositiveIntegerField()),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="student.student",
                    ),
                ),
                (
                    "shared_timetable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="analytics.sharedtimetable",
                    ),
                ),
            ],
        ),
    ]
