name: Bug Report
description: File a Bug Report
labels: [bug]
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: How can we reproduce the problem?
      description: A clear and concise description of what the problem is.
      value: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Expectations
    validations:
      required: true 
  - type: dropdown
    id: version
    attributes:
      label: OS Version
      description: Which OS were you using?
      options:
        - MacOS
        - Windows
        - Linux
        - Other
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: Which browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Additional Information
      description: |
        Please copy and paste any relevant log output or screenshot. 
        This will be automatically formatted into code, so no need for backticks.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: Add any other context or screenshots about the feature request here.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/jhuopensource/semesterly/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow Semester.ly's Code of Conduct
          required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!