# Generated by Django 2.2.18 on 2021-06-20 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0024_django_22_upgrade'),
        ('timetable', '0033_section_course_section_id'),
    ]

    operations = [
    ]
