# Generated by Django 2.2.18 on 2021-09-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0033_auto_20210724_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_food', models.TextField(null=True)),
                ('favorite_movie', models.TextField(null=True)),
                ('least_favorite_num', models.IntegerField(null=True)),
            ],
        ),
    ]
