# Generated by Django 2.2.18 on 2021-09-21 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0034_mockmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockmodel',
            name='student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
