# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2021-03-04 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0034_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('fav_book', models.CharField(max_length=255, null=True)),
                ('fav_lang', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
