# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2021-02-26 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0034_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yeet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('favorite_song', models.CharField(max_length=255, null=True)),
                ('favorite_artist', models.CharField(max_length=255, null=True)),
                ('is_will_bad', models.BooleanField(default=True)),
            ],
        ),
    ]
