# Generated by Django 2.2.18 on 2021-09-19 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0034_student_favorite_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='favorite_num',
        ),
    ]
