# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-01 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0034_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='favorite_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
