# Generated by Django 3.2.7 on 2021-11-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0034_auto_20210920_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalevent',
            name='color',
            field=models.CharField(default='#D4DBC8', max_length=7),
        ),
        migrations.AddField(
            model_name='personalevent',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
    ]
