# Generated by Django 2.2.18 on 2021-06-20 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_django_22_upgrade'),
        ('student', '0034_merge'),
    ]

    operations = [
    ]
