# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-02 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0035_student_favorite_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='favorite_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
