# Generated by Django 2.2.18 on 2021-09-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0035_remove_student_favorite_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreeColors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color1', models.CharField(default='red', max_length=255)),
                ('color2', models.CharField(default='green', max_length=255)),
                ('color3', models.CharField(default='blue', max_length=255)),
            ],
        ),
    ]
