# Generated by Django 2.2.18 on 2021-09-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0035_remove_student_favorite_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='favorite_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
