# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2021-02-27 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0036_auto_20210225_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fav_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
