# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-06 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0036_auto_20210602_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('director_name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
