# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2021-03-05 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0037_auto_20210227_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed', models.NullBooleanField()),
                ('chair', models.NullBooleanField()),
                ('desk', models.NullBooleanField()),
            ],
        ),
    ]
