# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-06 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0037_favouritemovie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouritemovie',
            name='release_date',
        ),
        migrations.AddField(
            model_name='favouritemovie',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
