# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-06 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0038_auto_20210606_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('director_name', models.CharField(max_length=100)),
                ('release_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='favouritemovie',
            name='student',
        ),
        migrations.DeleteModel(
            name='FavouriteMovie',
        ),
    ]
