# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2021-03-05 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0039_auto_20210305_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='bed',
            field=models.CharField(default=b'', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='chair',
            field=models.CharField(default=b'', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='desk',
            field=models.CharField(default=b'', max_length=255, null=True),
        ),
    ]
