name: Backend Linter

on:
  push:
    branches:
      - prod
      - develop
      - feature/enhance-custom-events
  pull_request:
    branches:
      - prod
      - develop
      - feature/enhance-custom-events

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          version: 21.12b0
